### ISSUE TITLE
Implementation of ESR and 2SI Encoders

### ISSUE THREAD

**Issue by msche** [ogmacorp/OgmaNeo2#40]
I just started looking at the OgmaNeo2 implementation and trying to understand how it works. Within the draft paper, you mention 2 algorithms to encode 2SI and ESR. While going through the code, I only see an implementation of a ImageEncoder. Is that using ESR, 2SI or a different algorithm

**Comment by 222464** [comment]
Hi,

OgmaNeo2 is outdated now, we recommend using [AOgmaNeo](https://github.com/ogmacorp/AOgmaNeo) instead.

The implementation of the encoder in AOgmaNeo is [here](https://github.com/ogmacorp/AOgmaNeo/blob/master/source/aogmaneo/encoder.cpp).

In AOgmaNeo, the encoders in the hierarchy use ESR, and the ImageEncoder included there uses self-organizing maps.

I have also updated the OgmaNeo2 README file to point to AOgmaNeo as a replacement.

Let me know if you have any other questions!

**Comment by msche** [comment]
Thanks for the quick response.
